name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2

    - name: Get .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-rc.2.21463.7'

    - name: dotnet publish
      run: |
        dotnet publish -c Release --self-contained -r linux-x64

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: themesofdotnetv2
        publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE  }}        
        package: bin/Release/net6.0/linux-x64/publish
