name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2

    - name: Get .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-rc.2.21463.7'

    - name: dotnet publish
      run: |
        dotnet publish -c Release --self-contained -r linux-x86

  #   - name: Authenticate with ACR
  #     uses: azure/docker-login@v1
  #     with:
  #       login-server: ${{ secrets.AZURE_ACR_SERVER }}
  #       username: ${{ secrets.AZURE_ACR_USER_NAME }}
  #       password: ${{ secrets.AZURE_ACR_PASSWORD }}

  #   - name: Docker Build & Push to ACR
  #     run: |
  #       docker build . -t ${{ secrets.AZURE_ACR_SERVER }}/themesofdotnet:${{ github.sha }}
  #       docker push ${{ secrets.AZURE_ACR_SERVER }}/themesofdotnet:${{ github.sha }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Deploy to Azure Web App
  #     id: deploy-to-webapp
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: 'themesofdotnetv2'
  #       publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
  #       images: '${{ secrets.AZURE_ACR_SERVER }}/themesofdotnet:${{ github.sha }}'

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: themesofdotnetv2
        publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE  }}        
        package: bin/Release/net6.0/linux-x86/publish
